## Content list

#### 1. Import libraries
#### 2. Import data
#### 3. Data cleaning
#### 4. Export data

## 1. Import libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import LSTM

## 2. Import data

In [2]:
# Turn project folder path into a string
path = r'C:\Users\Admin\Desktop\Data Analysis\Maching Learning\Climate_Win'

In [3]:
path

'C:\\Users\\Admin\\Desktop\\Data Analysis\\Maching Learning\\Climate_Win'

In [6]:
# Import weather data
df_cw = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'Dataset-weather-prediction-dataset-processed.csv'))

In [7]:
# Check output
df_cw.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [8]:
# Check shape
df_cw.shape

(22950, 170)

In [9]:
# Import climatewin prediction data
df_cw_pred = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

In [10]:
# Check output
df_cw_pred.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [11]:
# Check shape
df_cw_pred.shape

(22950, 16)

## 3. Data cleaning

In [12]:
# Dropping date and month column for df_cw
df_cw_nodate = df_cw.drop(['DATE','MONTH'], axis=1)

In [13]:
# Check output
df_cw_nodate

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [16]:
# Remove all the columns containing the name of three cities: GDANSK, ROMA, TOURS which don't exist in Pleasant weather data set
# Create a pattern 
pattern=r'(GDANSK|ROMA|TOURS)'

# Filter the columns to remove
columns_to_remove=df_cw_nodate.filter(regex=pattern).columns

In [17]:
# Check columns_to_remove
columns_to_remove

Index(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation',
       'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min',
       'GDANSK_temp_max', 'ROMA_cloud_cover', 'ROMA_wind_speed',
       'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean',
       'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure',
       'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean',
       'TOURS_temp_min', 'TOURS_temp_max'],
      dtype='object')

In [18]:
# Remove the columns and create a new data set
df_cw_nodate_1=df_cw_nodate.drop(columns=columns_to_remove, inplace=False)

In [19]:
# Check output
df_cw_nodate_1

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [53]:
# Check for missing value
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print (df_cw_nodate_1.isnull().sum())

BASEL_cloud_cover              0
BASEL_wind_speed               0
BASEL_humidity                 0
BASEL_pressure                 0
BASEL_global_radiation         0
BASEL_precipitation            0
BASEL_snow_depth               0
BASEL_sunshine                 0
BASEL_temp_mean                0
BASEL_temp_min                 0
BASEL_temp_max                 0
BELGRADE_cloud_cover           0
BELGRADE_humidity              0
BELGRADE_pressure              0
BELGRADE_global_radiation      0
BELGRADE_precipitation         0
BELGRADE_sunshine              0
BELGRADE_temp_mean             0
BELGRADE_temp_min              0
BELGRADE_temp_max              0
BUDAPEST_cloud_cover           0
BUDAPEST_humidity              0
BUDAPEST_pressure              0
BUDAPEST_global_radiation      0
BUDAPEST_precipitation         0
BUDAPEST_sunshine              0
BUDAPEST_temp_mean             0
BUDAPEST_temp_min              0
BUDAPEST_temp_max              0
DEBILT_cloud_cover             0
DEBILT_wind_speed              0
DEBILT_humidity                0
DEBILT_pressure                0
DEBILT_global_radiation        0
DEBILT_precipitation           0
DEBILT_sunshine                0
DEBILT_temp_mean               0
DEBILT_temp_min                0
DEBILT_temp_max                0
DUSSELDORF_cloud_cover         0
DUSSELDORF_wind_speed          0
DUSSELDORF_humidity            0
DUSSELDORF_pressure            0
DUSSELDORF_global_radiation    0
DUSSELDORF_precipitation       0
DUSSELDORF_snow_depth          0
DUSSELDORF_sunshine            0
DUSSELDORF_temp_mean           0
DUSSELDORF_temp_min            0
DUSSELDORF_temp_max            0
HEATHROW_cloud_cover           0
HEATHROW_humidity              0
HEATHROW_pressure              0
HEATHROW_global_radiation      0
HEATHROW_precipitation         0
HEATHROW_snow_depth            0
HEATHROW_sunshine              0
HEATHROW_temp_mean             0
HEATHROW_temp_min              0
HEATHROW_temp_max              0
KASSEL_wind_speed              0
KASSEL_humidity                0
KASSEL_pressure                0
KASSEL_global_radiation        0
KASSEL_precipitation           0
KASSEL_sunshine                0
KASSEL_temp_mean               0
KASSEL_temp_min                0
KASSEL_temp_max                0
LJUBLJANA_cloud_cover          0
LJUBLJANA_wind_speed           0
LJUBLJANA_humidity             0
LJUBLJANA_pressure             0
LJUBLJANA_global_radiation     0
LJUBLJANA_precipitation        0
LJUBLJANA_sunshine             0
LJUBLJANA_temp_mean            0
LJUBLJANA_temp_min             0
LJUBLJANA_temp_max             0
MAASTRICHT_cloud_cover         0
MAASTRICHT_wind_speed          0
MAASTRICHT_humidity            0
MAASTRICHT_pressure            0
MAASTRICHT_global_radiation    0
MAASTRICHT_precipitation       0
MAASTRICHT_sunshine            0
MAASTRICHT_temp_mean           0
MAASTRICHT_temp_min            0
MAASTRICHT_temp_max            0
MADRID_cloud_cover             0
MADRID_wind_speed              0
MADRID_humidity                0
MADRID_pressure                0
MADRID_global_radiation        0
MADRID_precipitation           0
MADRID_sunshine                0
MADRID_temp_mean               0
MADRID_temp_min                0
MADRID_temp_max                0
MUNCHENB_cloud_cover           0
MUNCHENB_humidity              0
MUNCHENB_global_radiation      0
MUNCHENB_precipitation         0
MUNCHENB_snow_depth            0
MUNCHENB_sunshine              0
MUNCHENB_temp_mean             0
MUNCHENB_temp_min              0
MUNCHENB_temp_max              0
OSLO_cloud_cover               0
OSLO_wind_speed                0
OSLO_humidity                  0
OSLO_pressure                  0
OSLO_global_radiation          0
OSLO_precipitation             0
OSLO_snow_depth                0
OSLO_sunshine                  0
OSLO_temp_mean                 0
OSLO_temp_min                  0
OSLO_temp_max                  0
SONNBLICK_cloud_cover          0
SONNBLICK_wind_speed           0
SONNBLICK_humidity             0
SONNBLICK_pressure             0
SONNBLICK_global_radiation     0
SONNBLICK_precipitation        0
SONNBLICK_sunshine             0
SONNBLICK_temp_mean            0
SONNBLICK_temp_min             0
SONNBLICK_temp_max             0
STOCKHOLM_cloud_cover          0
STOCKHOLM_pressure             0
STOCKHOLM_global_radiation     0
STOCKHOLM_precipitation        0
STOCKHOLM_sunshine             0
STOCKHOLM_temp_mean            0
STOCKHOLM_temp_min             0
STOCKHOLM_temp_max             0
VALENTIA_cloud_cover           0
VALENTIA_humidity              0
VALENTIA_pressure              0
VALENTIA_global_radiation      0
VALENTIA_precipitation         0
VALENTIA_snow_depth            0
VALENTIA_sunshine              0
VALENTIA_temp_mean             0
VALENTIA_temp_min              0
VALENTIA_temp_max              0
dtype: int64

#### 6 stations with missing windspeed column. 
(BELGRADE, BUDAPEST, HEATHROW, MUNCHENB, STOCKHOLM, VALENTIA)
#### 9 stations with missing snow_depth column. 
(BELGRADE, BUDAPEST, DEBILT, KASSEL, LJUBLJANA, MAASTRICHT, MADRID, SONNBLICK, STOCKHOLM)
#### 1 station with misisng cloud_cover column. 
(KASSEL)
#### 1 station with misisng humidity column. 
(STOCKHOLM)
#### 1 station with misisng pressure column. 
(MUNCHENB)

In [54]:
# Remove all the columns containing the two observations: wind_speed and snow_depth  
# Create a pattern 
pattern_1=r'(wind_speed|snow_depth)'

# Filter the columns to remove
columns_to_remove_1=df_cw_nodate_1.filter(regex=pattern_1).columns

In [55]:
# Check columns_to_remove_1
columns_to_remove_1

Index(['BASEL_wind_speed', 'BASEL_snow_depth', 'DEBILT_wind_speed',
       'DUSSELDORF_wind_speed', 'DUSSELDORF_snow_depth', 'HEATHROW_snow_depth',
       'KASSEL_wind_speed', 'LJUBLJANA_wind_speed', 'MAASTRICHT_wind_speed',
       'MADRID_wind_speed', 'MUNCHENB_snow_depth', 'OSLO_wind_speed',
       'OSLO_snow_depth', 'SONNBLICK_wind_speed', 'VALENTIA_snow_depth'],
      dtype='object')

In [56]:
# Remove the columns
df_cw_nodate_2=df_cw_nodate_1.drop(columns=columns_to_remove_1, inplace=False)

In [57]:
# Check output
df_cw_nodate_2

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,21.4,2,...,14.2,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22946,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,21.9,0,...,14.3,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22947,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,22.4,2,...,14.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22948,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,21.1,1,...,12.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22949,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,19.2,4,...,12.6,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5

In [58]:
# Add three new columns cloud_cover, pressure and humidity for three locations and copy the values from the closest weather staions
df_cw_nodate_2[['KASSEL_cloud_cover', 'MUNCHENB_pressue', 'STOCKHOLM_humidity']]=df_cw_nodate_2[['LJUBLJANA_cloud_cover', 'SONNBLICK_pressure', 'OSLO_humidity']].copy()

In [59]:
# Check output
df_cw_nodate_2

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max,KASSEL_cloud_cover,MUNCHENB_pressue,STOCKHOLM_humidity
0,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,10.9,1,...,1.0003,0.45,0.34,4.7,8.5,6.0,10.9,8,1.0304,0.98
1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,10.1,6,...,1.0007,0.25,0.84,0.7,8.9,5.6,12.1,6,1.0292,0.62
2,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,9.9,6,...,1.0096,0.17,0.08,0.1,10.5,8.1,12.9,8,1.0320,0.69
3,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,10.6,8,...,1.0184,0.13,0.98,0.0,7.4,7.3,10.6,6,1.0443,0.98
4,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,1.0328,0.46,0.00,5.7,5.7,3.0,8.4,7,1.0430,0.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,21.4,2,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,4,1.0263,0.98
22946,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,21.9,0,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,1.00
22947,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,22.4,2,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.85
22948,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,21.1,1,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.94
22949,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,19.2,4,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.97

In [74]:
# Check columns
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_cw_nodate_2.dtypes)

BASEL_cloud_cover                int64
BASEL_humidity                 float64
BASEL_pressure                 float64
BASEL_global_radiation         float64
BASEL_precipitation            float64
BASEL_sunshine                 float64
BASEL_temp_mean                float64
BASEL_temp_min                 float64
BASEL_temp_max                 float64
BELGRADE_cloud_cover             int64
BELGRADE_humidity              float64
BELGRADE_pressure              float64
BELGRADE_global_radiation      float64
BELGRADE_precipitation         float64
BELGRADE_sunshine              float64
BELGRADE_temp_mean             float64
BELGRADE_temp_min              float64
BELGRADE_temp_max              float64
BUDAPEST_cloud_cover             int64
BUDAPEST_humidity              float64
BUDAPEST_pressure              float64
BUDAPEST_global_radiation      float64
BUDAPEST_precipitation         float64
BUDAPEST_sunshine              float64
BUDAPEST_temp_mean             float64
BUDAPEST_temp_min              float64
BUDAPEST_temp_max              float64
DEBILT_cloud_cover               int64
DEBILT_humidity                float64
DEBILT_pressure                float64
DEBILT_global_radiation        float64
DEBILT_precipitation           float64
DEBILT_sunshine                float64
DEBILT_temp_mean               float64
DEBILT_temp_min                float64
DEBILT_temp_max                float64
DUSSELDORF_cloud_cover           int64
DUSSELDORF_humidity            float64
DUSSELDORF_pressure            float64
DUSSELDORF_global_radiation    float64
DUSSELDORF_precipitation       float64
DUSSELDORF_sunshine            float64
DUSSELDORF_temp_mean           float64
DUSSELDORF_temp_min            float64
DUSSELDORF_temp_max            float64
HEATHROW_cloud_cover             int64
HEATHROW_humidity              float64
HEATHROW_pressure              float64
HEATHROW_global_radiation      float64
HEATHROW_precipitation         float64
HEATHROW_sunshine              float64
HEATHROW_temp_mean             float64
HEATHROW_temp_min              float64
HEATHROW_temp_max              float64
KASSEL_humidity                float64
KASSEL_pressure                float64
KASSEL_global_radiation        float64
KASSEL_precipitation           float64
KASSEL_sunshine                float64
KASSEL_temp_mean               float64
KASSEL_temp_min                float64
KASSEL_temp_max                float64
LJUBLJANA_cloud_cover            int64
LJUBLJANA_humidity             float64
LJUBLJANA_pressure             float64
LJUBLJANA_global_radiation     float64
LJUBLJANA_precipitation        float64
LJUBLJANA_sunshine             float64
LJUBLJANA_temp_mean            float64
LJUBLJANA_temp_min             float64
LJUBLJANA_temp_max             float64
MAASTRICHT_cloud_cover           int64
MAASTRICHT_humidity            float64
MAASTRICHT_pressure            float64
MAASTRICHT_global_radiation    float64
MAASTRICHT_precipitation       float64
MAASTRICHT_sunshine            float64
MAASTRICHT_temp_mean           float64
MAASTRICHT_temp_min            float64
MAASTRICHT_temp_max            float64
MADRID_cloud_cover               int64
MADRID_humidity                float64
MADRID_pressure                float64
MADRID_global_radiation        float64
MADRID_precipitation           float64
MADRID_sunshine                float64
MADRID_temp_mean               float64
MADRID_temp_min                float64
MADRID_temp_max                float64
MUNCHENB_cloud_cover             int64
MUNCHENB_humidity              float64
MUNCHENB_global_radiation      float64
MUNCHENB_precipitation         float64
MUNCHENB_sunshine              float64
MUNCHENB_temp_mean             float64
MUNCHENB_temp_min              float64
MUNCHENB_temp_max              float64
OSLO_cloud_cover                 int64
OSLO_humidity                  float64
OSLO_pressure                  float64
OSLO_global_radiation          float64
OSLO_precipitation             float64
OSLO_sunshine                  float64
OSLO_temp_mean                 float64
OSLO_temp_min                  float64
OSLO_temp_max                  float64
SONNBLICK_cloud_cover            int64
SONNBLICK_humidity             float64
SONNBLICK_pressure             float64
SONNBLICK_global_radiation     float64
SONNBLICK_precipitation        float64
SONNBLICK_sunshine             float64
SONNBLICK_temp_mean            float64
SONNBLICK_temp_min             float64
SONNBLICK_temp_max             float64
STOCKHOLM_cloud_cover            int64
STOCKHOLM_pressure             float64
STOCKHOLM_global_radiation     float64
STOCKHOLM_precipitation        float64
STOCKHOLM_sunshine             float64
STOCKHOLM_temp_mean            float64
STOCKHOLM_temp_min             float64
STOCKHOLM_temp_max             float64
VALENTIA_cloud_cover             int64
VALENTIA_humidity              float64
VALENTIA_pressure              float64
VALENTIA_global_radiation      float64
VALENTIA_precipitation         float64
VALENTIA_sunshine              float64
VALENTIA_temp_mean             float64
VALENTIA_temp_min              float64
VALENTIA_temp_max              float64
KASSEL_cloud_cover               int64
MUNCHENB_pressue               float64
STOCKHOLM_humidity             float64
dtype: object

In [78]:
# Re-sort the columns in order
df_cw_sort = df_cw_nodate_2[sorted(df_cw_nodate_2.columns)]

In [80]:
# Check if columns is re-sorted
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_cw_sort.dtypes)

BASEL_cloud_cover                int64
BASEL_global_radiation         float64
BASEL_humidity                 float64
BASEL_precipitation            float64
BASEL_pressure                 float64
BASEL_sunshine                 float64
BASEL_temp_max                 float64
BASEL_temp_mean                float64
BASEL_temp_min                 float64
BELGRADE_cloud_cover             int64
BELGRADE_global_radiation      float64
BELGRADE_humidity              float64
BELGRADE_precipitation         float64
BELGRADE_pressure              float64
BELGRADE_sunshine              float64
BELGRADE_temp_max              float64
BELGRADE_temp_mean             float64
BELGRADE_temp_min              float64
BUDAPEST_cloud_cover             int64
BUDAPEST_global_radiation      float64
BUDAPEST_humidity              float64
BUDAPEST_precipitation         float64
BUDAPEST_pressure              float64
BUDAPEST_sunshine              float64
BUDAPEST_temp_max              float64
BUDAPEST_temp_mean             float64
BUDAPEST_temp_min              float64
DEBILT_cloud_cover               int64
DEBILT_global_radiation        float64
DEBILT_humidity                float64
DEBILT_precipitation           float64
DEBILT_pressure                float64
DEBILT_sunshine                float64
DEBILT_temp_max                float64
DEBILT_temp_mean               float64
DEBILT_temp_min                float64
DUSSELDORF_cloud_cover           int64
DUSSELDORF_global_radiation    float64
DUSSELDORF_humidity            float64
DUSSELDORF_precipitation       float64
DUSSELDORF_pressure            float64
DUSSELDORF_sunshine            float64
DUSSELDORF_temp_max            float64
DUSSELDORF_temp_mean           float64
DUSSELDORF_temp_min            float64
HEATHROW_cloud_cover             int64
HEATHROW_global_radiation      float64
HEATHROW_humidity              float64
HEATHROW_precipitation         float64
HEATHROW_pressure              float64
HEATHROW_sunshine              float64
HEATHROW_temp_max              float64
HEATHROW_temp_mean             float64
HEATHROW_temp_min              float64
KASSEL_cloud_cover               int64
KASSEL_global_radiation        float64
KASSEL_humidity                float64
KASSEL_precipitation           float64
KASSEL_pressure                float64
KASSEL_sunshine                float64
KASSEL_temp_max                float64
KASSEL_temp_mean               float64
KASSEL_temp_min                float64
LJUBLJANA_cloud_cover            int64
LJUBLJANA_global_radiation     float64
LJUBLJANA_humidity             float64
LJUBLJANA_precipitation        float64
LJUBLJANA_pressure             float64
LJUBLJANA_sunshine             float64
LJUBLJANA_temp_max             float64
LJUBLJANA_temp_mean            float64
LJUBLJANA_temp_min             float64
MAASTRICHT_cloud_cover           int64
MAASTRICHT_global_radiation    float64
MAASTRICHT_humidity            float64
MAASTRICHT_precipitation       float64
MAASTRICHT_pressure            float64
MAASTRICHT_sunshine            float64
MAASTRICHT_temp_max            float64
MAASTRICHT_temp_mean           float64
MAASTRICHT_temp_min            float64
MADRID_cloud_cover               int64
MADRID_global_radiation        float64
MADRID_humidity                float64
MADRID_precipitation           float64
MADRID_pressure                float64
MADRID_sunshine                float64
MADRID_temp_max                float64
MADRID_temp_mean               float64
MADRID_temp_min                float64
MUNCHENB_cloud_cover             int64
MUNCHENB_global_radiation      float64
MUNCHENB_humidity              float64
MUNCHENB_precipitation         float64
MUNCHENB_pressue               float64
MUNCHENB_sunshine              float64
MUNCHENB_temp_max              float64
MUNCHENB_temp_mean             float64
MUNCHENB_temp_min              float64
OSLO_cloud_cover                 int64
OSLO_global_radiation          float64
OSLO_humidity                  float64
OSLO_precipitation             float64
OSLO_pressure                  float64
OSLO_sunshine                  float64
OSLO_temp_max                  float64
OSLO_temp_mean                 float64
OSLO_temp_min                  float64
SONNBLICK_cloud_cover            int64
SONNBLICK_global_radiation     float64
SONNBLICK_humidity             float64
SONNBLICK_precipitation        float64
SONNBLICK_pressure             float64
SONNBLICK_sunshine             float64
SONNBLICK_temp_max             float64
SONNBLICK_temp_mean            float64
SONNBLICK_temp_min             float64
STOCKHOLM_cloud_cover            int64
STOCKHOLM_global_radiation     float64
STOCKHOLM_humidity             float64
STOCKHOLM_precipitation        float64
STOCKHOLM_pressure             float64
STOCKHOLM_sunshine             float64
STOCKHOLM_temp_max             float64
STOCKHOLM_temp_mean            float64
STOCKHOLM_temp_min             float64
VALENTIA_cloud_cover             int64
VALENTIA_global_radiation      float64
VALENTIA_humidity              float64
VALENTIA_precipitation         float64
VALENTIA_pressure              float64
VALENTIA_sunshine              float64
VALENTIA_temp_max              float64
VALENTIA_temp_mean             float64
VALENTIA_temp_min              float64
dtype: object

In [82]:
# Check final shape of dataframe
df_cw_sort.shape

(22950, 135)

In [83]:
# Dropping date column for df_cw_pred
df_cw_pred_nodate = df_cw_pred.drop(['DATE'], axis=1)

In [84]:
# Check output
df_cw_pred_nodate.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [85]:
# Check shape
df_cw_pred_nodate.shape

(22950, 15)

## 4. Export data

In [86]:
# Export df_cw_sort dataframe
df_cw_sort.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'climatewin_cleaned.csv'), index=False)

In [87]:
# Export df_cw_pred_nodate dataframe
df_cw_pred_nodate.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'climatewin_answers_cleaned.csv'), index=False)